#!/sbin/sh
rm -rf /system/addon.d/70-gapps.sh
rm -rf /system/addon.d/71-faceunlock.sh
rm -rf /system/addon.d/71-gapps-faceunlock.sh
rm -rf /system/addon.d/74-googlecamera.sh
rm -rf /system/addon.d/74-googlegallery.sh
rm -rf /system/addon.d/75-googlegallery.sh
rm -rf /system/addon.d/78-chromebrowser.sh
rm -rf /system/bin/wmdsi
rm -rf /system/etc/default-permissions/default-permissions.xml
rm -rf /system/etc/default-permissions/opengapps-permissions.xml
rm -rf /system/etc/g.prop
rm -rf /system/etc/permissions/com.google.android.camera.experimental2015.xml
rm -rf /system/etc/permissions/com.google.android.camera.experimental2016.xml
rm -rf /system/etc/permissions/com.google.android.camera2.xml
rm -rf /system/etc/permissions/com.google.android.dialer.support.xml
rm -rf /system/etc/permissions/com.google.android.maps.xml
rm -rf /system/etc/permissions/com.google.android.media.effects.xml
rm -rf /system/etc/permissions/com.google.android.pano.v1.xml
rm -rf /system/etc/permissions/com.google.widevine.software.drm.xml
rm -rf /system/etc/permissions/features.xml
rm -rf /system/etc/preferred-apps/google.xml
rm -rf /system/etc/sysconfig/google.xml
rm -rf /system/etc/sysconfig/google_build.xml
rm -rf /system/etc/sysconfig/google_vr_build.xml
rm -rf /system/etc/sysconfig/whitelist_com.android.omadm.service.xml
rm -rf /system/etc/updatecmds/google_generic_update.txt
rm -rf /system/framework/com.google.android.camera.experimental2015.jar
rm -rf /system/framework/com.google.android.camera.experimental2016.jar
rm -rf /system/framework/com.google.android.camera2.jar
rm -rf /system/framework/com.google.android.dialer.support.jar
rm -rf /system/framework/com.google.android.maps.jar
rm -rf /system/framework/com.google.android.media.effects.jar
rm -rf /system/framework/com.google.android.pano.v1.jar
rm -rf /system/framework/com.google.widevine.software.drm.jar
rm -rf /system/lib/lib_dic_.so
rm -rf /system/lib/libAppDataSearch.so
rm -rf /system/lib/libbitmap_parcel.so
rm -rf /system/lib/libchrome.so
rm -rf /system/lib/libchromeview.so
rm -rf /system/lib/libconscrypt_gmscore_jni.so
rm -rf /system/lib/libcrashreporter.so
rm -rf /system/lib/libdocscanner.so
rm -rf /system/lib/libdocsimageutils.so
rm -rf /system/lib/libearthandroid.so
rm -rf /system/lib/libearthmobile.so
rm -rf /system/lib/libEnjemailuri.so
rm -rf /system/lib/libennjcon.so
rm -rf /system/lib/libennjubase.so
rm -rf /system/lib/libennjyomi.so
rm -rf /system/lib/libfacelock_jni.so
rm -rf /system/lib/libfacenet.so
rm -rf /system/lib/libfacetracker.so
rm -rf /system/lib/libfilterframework_jni.so
rm -rf /system/lib/libfilterpack_facedetect.so
rm -rf /system/lib/libflint_engine_jni_api.so
rm -rf /system/lib/libfoxit.so
rm -rf /system/lib/libframesequence.so
rm -rf /system/lib/libfrsdk.so
rm -rf /system/lib/libgames_rtmp_jni.so
rm -rf /system/lib/libgcam.so
rm -rf /system/lib/libgcam_swig_jni.so
rm -rf /system/lib/libgcastv2.so
rm -rf /system/lib/libgcomm_jni.so
rm -rf /system/lib/libgmm-jni.so
rm -rf /system/lib/libgms-ocrclient.so
rm -rf /system/lib/libgmscore.so
rm -rf /system/lib/libgoggles_clientvision.so
rm -rf /system/lib/libgoogle_.so
rm -rf /system/lib/libgtalk_jni.so
rm -rf /system/lib/libgtalk_stabilize.so
rm -rf /system/lib/libiwnn.so
rm -rf /system/lib/libjgcastservice.so
rm -rf /system/lib/libjni_eglfence.so
rm -rf /system/lib/libjni_filtershow_filters.so
rm -rf /system/lib/libjni_googlepinyinime_.so
rm -rf /system/lib/libjni_koreanime.so
rm -rf /system/lib/libjni_latinime.so
rm -rf /system/lib/libjni_latinimegoogle.so
rm -rf /system/lib/libjni_t13n_shared_engine.so
rm -rf /system/lib/libjni_tinyplanet.so
rm -rf /system/lib/libjni_unbundled_latinimegoogle.so
rm -rf /system/lib/liblightcycle.so
rm -rf /system/lib/liblinearalloc.so
rm -rf /system/lib/libm2ts_player.so
rm -rf /system/lib/libmicro_hotword_jni.so
rm -rf /system/lib/libmoviemaker-jni.so
rm -rf /system/lib/libnativehelper_compat.so
rm -rf /system/lib/libnativehelper_compat_libc++.so
rm -rf /system/lib/libndk1.so
rm -rf /system/lib/libnetjni.so
rm -rf /system/lib/libnjaddress.so
rm -rf /system/lib/libnjcon.so
rm -rf /system/lib/libnjemoji.so
rm -rf /system/lib/libnjexyomi.so
rm -rf /system/lib/libnjfzk.so
rm -rf /system/lib/libnjkaomoji.so
rm -rf /system/lib/libnjname.so
rm -rf /system/lib/libnjtan.so
rm -rf /system/lib/libnjubase.so
rm -rf /system/lib/libnjubaseidx1.so
rm -rf /system/lib/libnjubaseidx2.so
rm -rf /system/lib/libocrclient.so
rm -rf /system/lib/libpatts_engine_.so
rm -rf /system/lib/libphotoeditor_native.so
rm -rf /system/lib/libpicowrapper.so
rm -rf /system/lib/libplus_jni_v8.so
rm -rf /system/lib/librectifier.so
rm -rf /system/lib/librefocus.so
rm -rf /system/lib/librs.antblur.so
rm -rf /system/lib/librs.antblur_.so
rm -rf /system/lib/librs.drama.so
rm -rf /system/lib/librs.film_base.so
rm -rf /system/lib/librs.fixedframe.so
rm -rf /system/lib/librs.grey.so
rm -rf /system/lib/librs.image_wrapper.so
rm -rf /system/lib/librs.layered_filter_f32.so
rm -rf /system/lib/librs.retrolux.so
rm -rf /system/lib/librsjni.so
rm -rf /system/lib/libRSSupport.so
rm -rf /system/lib/libspeexwrapper.so
rm -rf /system/lib/libspeexwrapper_ub.so
rm -rf /system/lib/libsslwrapper_jni.so
rm -rf /system/lib/libstlport_shared.so
rm -rf /system/lib/libvcdecoder_jni.so
rm -rf /system/lib/libvideochat_jni.so
rm -rf /system/lib/libvideochat_stabilize.so
rm -rf /system/lib/libvoicesearch.so
rm -rf /system/lib/libvorbisencoder.so
rm -rf /system/lib/libwebp_android.so
rm -rf /system/lib/libwebrtc_audio_coding.so
rm -rf /system/lib/libWhisper.so
rm -rf /system/lib/libWVphoneAPI.so
rm -rf /system/lib/modules/modules.dep.bb
rm -rf /system/lib64/lib_dic_.so
rm -rf /system/lib64/libAppDataSearch.so
rm -rf /system/lib64/libbitmap_parcel.so
rm -rf /system/lib64/libchrome.so
rm -rf /system/lib64/libchromeview.so
rm -rf /system/lib64/libconscrypt_gmscore_jni.so
rm -rf /system/lib64/libcrashreporter.so
rm -rf /system/lib64/libdocscanner.so
rm -rf /system/lib64/libdocsimageutils.so
rm -rf /system/lib64/libearthandroid.so
rm -rf /system/lib64/libearthmobile.so
rm -rf /system/lib64/libEnjemailuri.so
rm -rf /system/lib64/libennjcon.so
rm -rf /system/lib64/libennjubase.so
rm -rf /system/lib64/libennjyomi.so
rm -rf /system/lib64/libfacelock_jni.so
rm -rf /system/lib64/libfacenet.so
rm -rf /system/lib64/libfacetracker.so
rm -rf /system/lib64/libfilterframework_jni.so
rm -rf /system/lib64/libfilterpack_facedetect.so
rm -rf /system/lib64/libflint_engine_jni_api.so
rm -rf /system/lib64/libfoxit.so
rm -rf /system/lib64/libframesequence.so
rm -rf /system/lib64/libfrsdk.so
rm -rf /system/lib64/libgames_rtmp_jni.so
rm -rf /system/lib64/libgcam.so
rm -rf /system/lib64/libgcam_swig_jni.so
rm -rf /system/lib64/libgcastv2.so
rm -rf /system/lib64/libgcomm_jni.so
rm -rf /system/lib64/libgmm-jni.so
rm -rf /system/lib64/libgms-ocrclient.so
rm -rf /system/lib64/libgmscore.so
rm -rf /system/lib64/libgoggles_clientvision.so
rm -rf /system/lib64/libgoogle_.so
rm -rf /system/lib64/libgtalk_jni.so
rm -rf /system/lib64/libgtalk_stabilize.so
rm -rf /system/lib64/libiwnn.so
rm -rf /system/lib64/libjgcastservice.so
rm -rf /system/lib64/libjni_eglfence.so
rm -rf /system/lib64/libjni_filtershow_filters.so
rm -rf /system/lib64/libjni_googlepinyinime_.so
rm -rf /system/lib64/libjni_koreanime.so
rm -rf /system/lib64/libjni_latinime.so
rm -rf /system/lib64/libjni_latinimegoogle.so
rm -rf /system/lib64/libjni_t13n_shared_engine.so
rm -rf /system/lib64/libjni_tinyplanet.so
rm -rf /system/lib64/libjni_unbundled_latinimegoogle.so
rm -rf /system/lib64/liblightcycle.so
rm -rf /system/lib64/liblinearalloc.so
rm -rf /system/lib64/libm2ts_player.so
rm -rf /system/lib64/libmicro_hotword_jni.so
rm -rf /system/lib64/libmoviemaker-jni.so
rm -rf /system/lib64/libnativehelper_compat.so
rm -rf /system/lib64/libnativehelper_compat_libc++.so
rm -rf /system/lib64/libndk1.so
rm -rf /system/lib64/libnetjni.so
rm -rf /system/lib64/libnjaddress.so
rm -rf /system/lib64/libnjcon.so
rm -rf /system/lib64/libnjemoji.so
rm -rf /system/lib64/libnjexyomi.so
rm -rf /system/lib64/libnjfzk.so
rm -rf /system/lib64/libnjkaomoji.so
rm -rf /system/lib64/libnjname.so
rm -rf /system/lib64/libnjtan.so
rm -rf /system/lib64/libnjubase.so
rm -rf /system/lib64/libnjubaseidx1.so
rm -rf /system/lib64/libnjubaseidx2.so
rm -rf /system/lib64/libocrclient.so
rm -rf /system/lib64/libpatts_engine_.so
rm -rf /system/lib64/libphotoeditor_native.so
rm -rf /system/lib64/libpicowrapper.so
rm -rf /system/lib64/libplus_jni_v8.so
rm -rf /system/lib64/librectifier.so
rm -rf /system/lib64/librefocus.so
rm -rf /system/lib64/librs.antblur.so
rm -rf /system/lib64/librs.antblur_.so
rm -rf /system/lib64/librs.drama.so
rm -rf /system/lib64/librs.film_base.so
rm -rf /system/lib64/librs.fixedframe.so
rm -rf /system/lib64/librs.grey.so
rm -rf /system/lib64/librs.image_wrapper.so
rm -rf /system/lib64/librs.layered_filter_f32.so
rm -rf /system/lib64/librs.retrolux.so
rm -rf /system/lib64/librsjni.so
rm -rf /system/lib64/libRSSupport.so
rm -rf /system/lib64/libspeexwrapper.so
rm -rf /system/lib64/libspeexwrapper_ub.so
rm -rf /system/lib64/libsslwrapper_jni.so
rm -rf /system/lib64/libstlport_shared.so
rm -rf /system/lib64/libvcdecoder_jni.so
rm -rf /system/lib64/libvideochat_jni.so
rm -rf /system/lib64/libvideochat_stabilize.so
rm -rf /system/lib64/libvoicesearch.so
rm -rf /system/lib64/libvorbisencoder.so
rm -rf /system/lib64/libwebp_android.so
rm -rf /system/lib64/libwebrtc_audio_coding.so
rm -rf /system/lib64/libWhisper.so
rm -rf /system/lib64/libWVphoneAPI.so
rm -rf /system/lib64/modules/modules.dep.bb
rm -rf /system/usr/srec
rm -rf /system/vendor/lib/libfrsdk.so
rm -rf /system/vendor/lib64/libfrsdk.so
rm -rf /system/vendor/pittpatt
